version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.5.0
    working_directory: ~/repo
    branches:
      only:
        - master
    steps:
      - checkout
      - restore_cache:
          keys:
          - dependencies-{{ checksum "package.json" }}
          - dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "package.json" }}
      - run: cp env.example.js env.js
      - run: sed -i.bak "s/<k8s-master-ip>/${K8S_MASTER_IP}/g" env.js
      - run: sed -i.bak "s/<admin-token>/${ADMIN_TOKEN}" env.js
      - run: yarn start